In [1]:
import keras
import tensorflow
import pandas as pd
import numpy as np

Using TensorFlow backend.


In [2]:
df = pd.read_csv("sonar.csv",header=None)
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [3]:
df.describe()

0           1           2           3           4           5   \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.029164    0.038437    0.043832    0.053892    0.075202    0.104570   
std      0.022991    0.032960    0.038428    0.046528    0.055552    0.059105   
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200   
25%      0.013350    0.016450    0.018950    0.024375    0.038050    0.067025   
50%      0.022800    0.030800    0.034300    0.044050    0.062500    0.092150   
75%      0.035550    0.047950    0.057950    0.064500    0.100275    0.134125   
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300   

               6           7           8           9   ...          50  \
count  208.000000  208.000000  208.000000  208.000000  ...  208.000000   
mean     0.121747    0.134799    0.178003    0.208259  ...    0.016069   
std      0.061788    0.085152    0.118387    0.134416  ...    0.012008   
min      0.003300    0.005500    0.007500    0.011300  ...    0.000000   
25%      0.080900    0.080425    0.097025    0.111275  ...    0.008425   
50%      0.106950    0.112100    0.152250    0.182400  ...    0.013900   
75%      0.154000    0.169600    0.233425    0.268700  ...    0.020825   
max      0.372900    0.459000    0.682800    0.710600  ...    0.100400   

               51          52          53          54          55          56  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.013420    0.010709    0.010941    0.009290    0.008222    0.007820   
std      0.009634    0.007060    0.007301    0.007088    0.005736    0.005785   
min      0.000800    0.000500    0.001000    0.000600    0.000400    0.000300   
25%      0.007275    0.005075    0.005375    0.004150    0.004400    0.003700   
50%      0.011400    0.009550    0.009300    0.007500    0.006850    0.005950   
75%      0.016725    0.014900    0.014500    0.012100    0.010575    0.010425   
max      0.070900    0.039000    0.035200    0.044700    0.039400    0.035500   

               57          58          59  
count  208.000000  208.000000  208.000000  
mean     0.007949    0.007941    0.006507  
std      0.006470    0.006181    0.005031  
min      0.000300    0.000100    0.000600  
25%      0.003600    0.003675    0.003100  
50%      0.005800    0.006400    0.005300  
75%      0.010350    0.010325    0.008525  
max      0.044000    0.036400    0.043900  

[8 rows x 60 columns]

In [4]:
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [5]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
encoder =LabelEncoder()
y =encoder.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
def scaling(var):
    sc = StandardScaler()
    var_scale=sc.fit_transform(var)
    return var_scale
x = scaling(x)
x

array([[-0.39955135, -0.04064823, -0.02692565, ...,  0.06987027,
         0.17167808, -0.65894689],
       [ 0.70353822,  0.42163039,  1.05561832, ..., -0.47240644,
        -0.44455424, -0.41985233],
       [-0.12922901,  0.60106749,  1.72340448, ...,  1.30935987,
         0.25276128,  0.25758223],
       ...,
       [ 1.00438083,  0.16007801, -0.67384349, ...,  0.90652575,
        -0.03913824, -0.67887143],
       [ 0.04953255, -0.09539176,  0.13480381, ..., -0.00759783,
        -0.70402047, -0.34015415],
       [-0.13794908, -0.06497869, -0.78861924, ..., -0.6738235 ,
        -0.29860448,  0.99479044]])

In [7]:
x.shape

(208, 60)

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=7)

In [9]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [10]:
model = Sequential()
model.add(Dense(units=100, activation ="relu", kernel_initializer ="uniform",input_dim=60))
model.add(Dense(units=200, activation = "relu", kernel_initializer ="uniform"))
model.add(Dense(units=500, activation = "relu", kernel_initializer ="uniform"))
model.add(Dropout(rate=0.1))
model.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

In [11]:
model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

In [12]:
model.fit(x_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
166/166 [==============================] - 0s 737us/step - loss: 0.6419 - accuracy: 0.6386
Epoch 2/100
166/166 [==============================] - 0s 182us/step - loss: 0.3558 - accuracy: 0.8494
Epoch 3/100
166/166 [==============================] - 0s 177us/step - loss: 0.2253 - accuracy: 0.9096
Epoch 4/100
166/166 [==============================] - 0s 180us/step - loss: 0.1440 - accuracy: 0.9337
Epoch 5/100
166/166 [==============================] - 0s 174us/step - loss: 0.0741 - accuracy: 0.9699
Epoch 6/100
166/166 [==============================] - 0s 180us/step - loss: 0.0235 - accuracy: 1.0000
Epoch 7/100
166/166 [==============================] - ETA: 0s - loss: 0.0161 - accuracy: 1.00 - 0s 172us/step - loss: 0.0108 - accuracy: 1.0000
Epoch 8/100
166/166 [==============================] - 0s 180us/step - loss: 0.0045 - accuracy: 1.0000
Epoch 9/100
166/166 [==============================] - 0s 176us/step - loss: 0.0024 - accuracy: 1.0000
Epoch 10/100
166/166 [=========

Epoch 77/100
166/166 [==============================] - 0s 168us/step - loss: 4.1581e-05 - accuracy: 1.0000
Epoch 78/100
166/166 [==============================] - 0s 156us/step - loss: 3.9047e-05 - accuracy: 1.0000
Epoch 79/100
166/166 [==============================] - 0s 165us/step - loss: 3.4540e-05 - accuracy: 1.0000
Epoch 80/100
166/166 [==============================] - 0s 169us/step - loss: 3.9795e-05 - accuracy: 1.0000
Epoch 81/100
166/166 [==============================] - 0s 162us/step - loss: 3.3564e-05 - accuracy: 1.0000
Epoch 82/100
166/166 [==============================] - 0s 160us/step - loss: 3.4309e-05 - accuracy: 1.0000
Epoch 83/100
166/166 [==============================] - 0s 161us/step - loss: 3.3736e-05 - accuracy: 1.0000
Epoch 84/100
166/166 [==============================] - 0s 171us/step - loss: 3.1900e-05 - accuracy: 1.0000
Epoch 85/100
166/166 [==============================] - 0s 159us/step - loss: 3.1681e-05 - accuracy: 1.0000
Epoch 86/100
166/166 [======

In [13]:
y_pred = model.predict(x_test)
y_pred = (y_pred>0.5)
y_pred

array([[ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True]])

In [14]:
error_rate =model.evaluate(x_test,y_pred)

42/42 [==============================] - 0s 521us/step


In [15]:
error_rate

[0.0018955578340128774, 1.0]

In [16]:
from keras.models import load_model

model.save('my_model.h5',include_optimizer=False)  # creates a HDF5 file 'my_model.h5'

In [17]:
from tensorflow.keras.models import load_model

In [18]:
modele = load_model("my_model.h5")

In [19]:
Y_pred = modele.predict(x_test)
Y_pred = (y_pred>0.5)
Y_pred

array([[ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True]])

In [24]:
from sklearn.metrics import confusion_matrix,classification_report
def result():
    cm = confusion_matrix(y_pred,y_test)
    cr = classification_report(y_pred,y_test)
    print(cm)
    print(cr)
    return
result()

[[25  2]
 [ 2 13]]
              precision    recall  f1-score   support

       False       0.93      0.93      0.93        27
        True       0.87      0.87      0.87        15

    accuracy                           0.90        42
   macro avg       0.90      0.90      0.90        42
weighted avg       0.90      0.90      0.90        42



In [25]:
38/42

0.9047619047619048